# 스프링부트 서버 설정
server:
  port: 9000
  servlet.session.timeout: 1800   # 세션 타임아웃 : 초


# 스프링 설정
spring:
  profiles:
    include:
      - common    # 공통 설정
      - database  # database 설정
  jmx.default-domain: web2
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  jackson:
    default-property-inclusion: non_null

# JWT 설정
jwt:
  header: Authorization
  # secret: {secret key}
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  access-token-validity-in-seconds: 1800 # 초 단위
  refresh-token-validity-in-seconds: 604800

# 캐싱 변수
caching:
  ttl: 300000   # 캐싱의 Time to live

---
# 개발환경 프로파일
spring:
  config:
    activate:
      on-profile: dev

# 로그파일 위치
logging.file.name: ./logs/${spring.jmx.default-domain}


---
# 테스트 환경 프로파일
spring:
  config:
    activate:
      on-profile: test

# 로그파일 위치
logging.file.name: /usr/local/tomcat/logs/${spring.jmx.default-domain}


---
# 상용환경 프로파일
spring:
  config:
    activate:
      on-profile: alpha

# 스프링부트 서버 설정
server:
  port: 8080                      # 스프링부트 서버 포트
  #servlet.session.timeout: 5400   # 세션 타임아웃 : 초 (dev)
  servlet.session.timeout: 3600   # 세션 타임아웃 : 초 (real , test1)

# 로그파일 위치
logging.file.name: /usr/local/tomcat/logs/${spring.jmx.default-domain}


---
# 상용환경 프로파일
spring:
  config:
    activate:
      on-profile: real

# 로그파일 위치
logging.file.name: /usr/local/tomcat/logs/${spring.jmx.default-domain}


