# Database 프로파일

# p6spy - sql log spy
decorator:
  datasource:
    p6spy:
      enable-logging: false

# Mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: kr.co.glog.domain

# JPA
# spring:
#  jpa:
#    properties:
#              hibernate:
#        hbm2ddl:
#          auto: validate
#        show_sql: true
#       format_sql: true
#        enable_lazy_load_no_trans: true
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    database: mysql

---
# 개봘환경/테스트환경 프로파일
spring:
  config:
    activate:
      on-profile: dev, test
  # 데이터베이스
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://3.35.250.69:3306/app?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&enabledTLSProtocols=TLSv1.2
        username: app
        password: Q1w2e3r$
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 5
        max-lifetime: 240000
        maximum-pool-size: 20
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://3.35.250.69:3306/app?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&enabledTLSProtocols=TLSv1.2
        username: app
        password: Q1w2e3r$
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 5
        max-lifetime: 240000
        maximum-pool-size: 20
        domain-read-only: true
        connection-test-query: SELECT 1


